apiVersion: v1
kind: Service
metadata:
  #annotations:
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'sdfgfdsg'
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    #service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  creationTimestamp: "2022-01-07T00:22:45Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: nginx-prox-lb
  namespace: default
  resourceVersion: "2163"
  uid: a3631955-3bed-4f49-9074-f1f39d5b041c
spec:
  clusterIP: 10.100.69.23
  clusterIPs:
  - 10.100.69.23
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30126
    port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    protocol: TCP
    targetPort: 80
    name: https    
  selector:
    app: mysite
  sessionAffinity: None
  type: LoadBalancer
